[package]
name = "critical"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.43"
clap = { git = "https://github.com/clap-rs/clap/" }
metaflac = "0.2.4"
id3 = "0.6.4"
mp3-duration = "0.1.10"
walkdir = "2"
env_logger = "0.9.0"
graphql_client = { version = "0.10.0", features = ["reqwest-blocking"] }
reqwest = { version = "0.11", features = ["json", "blocking"] }
serde = "^1.0"
serde_json = "^1.0"
indicatif = "0.16.2"
itertools = "0.10.1"
cached = "0.25.0"
uuid = { version = "0.8", features = ["v4"] }
