[package]
name = "critical"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.52"
clap = { version = "3.0.2", features = ["derive"] }
metaflac = "0.2.4"
id3 = "1.0"
mp3-duration = "0.1.10"
walkdir = "2"
env_logger = "0.9.0"
graphql_client = { git = "https://github.com/graphql-rust/graphql-client", features = ["reqwest-blocking"] }
reqwest = { version = "0.11", features = ["json", "blocking"] }
serde = "^1.0"
serde_json = "^1.0"
indicatif = "0.16.2"
itertools = "0.10.1"
prettytable-rs = "^0.10"
uuid = { version = "0.8", features = ["v4"] }
enum_dispatch = "0.3.7"
postgres = "0.19.1"
lazy_static = "1.4.0"
